name: Build and Deploy Wisecow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/shubhamrahangdale/wisecow:latest . --no-cache

    - name: Push Docker image
      run: |
        docker push ghcr.io/shubhamrahangdale/wisecow:latest
    - name: Setup Kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/
